services:
  design-system:
    build:
      context: design-system
      target: build

  publish:
    build:
      context: design-system
      target: publish

  coverage:
    build:
      context: design-system
      target: coverage
    ports:
      - "63004:80"

  website:
    build: website
    ports:
      - "28005:5173"
    depends_on:
      - design-system
