services:
  design-system:
    build:
      context: design-system
      target: build

  publish:
    build:
      context: design-system
      target: publish

  website:
    build: website
    ports:
      - "3736:5173"
    depends_on:
      - design-system
